services:
  vehicle-mc-py:
    build:
      context: .
      dockerfile: vehicle/Dockerfile.demo

  vehicle-a-py:
    build:
      context: .
      dockerfile: vehicle/Dockerfile.demo

  vehicle-b-py:
    build:
      context: .
      dockerfile: vehicle/Dockerfile.demo

  vehicle-c-py:
    build:
      context: .
      dockerfile: vehicle/Dockerfile.demo
