FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir eclipse-zenoh

COPY vehicle/vehicle.py .
COPY vehicle/vehicle_demo.py .
COPY vehicle/cam_builder.py .
COPY vehicle/mcm_builder.py .
COPY vehicle/comms.py .
COPY vehicle/geo.py .
COPY vehicle/simulation.py .
COPY vehicle/simulation_demo.py .
COPY vehicle/protocol.py .
COPY vehicle/protocol_demo.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "vehicle_demo.py"]
